sudo: false
language: java

os:
  #not yet available for java - windows 
  - linux
  - osx

git:
  depth: 3
  lfs_skip_smudge: true

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

jdk:
  - openjdk10
  - openjdk11

#script: mvn '-Dtest=de.hpi.bpt.scylla.*Tests' test
script:
  mvn clean test

notifications:
  email: false
